/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleplugin;

import gradleplugin.task.CreateTag;
import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class GradlePlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("CreateTagTask", CreateTag.class);

    }
}
